"""Added other tables: books and userbooks

Revision ID: 46fd39cb2399
Revises: 
Create Date: 2026-05-26 21:24:13.687949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46fd39cb2399'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('author', sa.String(length=250), nullable=False),
    sa.Column('publisher', sa.String(length=250), nullable=False),
    sa.Column('isbn', sa.String(length=20), nullable=True),
    sa.Column('cover_id', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('year_published', sa.Integer(), nullable=True),
    sa.Column('genre', sa.String(length=250), nullable=False),
    sa.Column('length', sa.String(length=250), nullable=True),
    sa.Column('agg_enjoyment', sa.Float(), nullable=True),
    sa.Column('agg_aura', sa.Float(), nullable=False),
    sa.Column('persona_one', sa.String(length=250), nullable=False),
    sa.Column('persona_two', sa.String(length=250), nullable=True),
    sa.Column('persona_three', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cover_id'),
    sa.UniqueConstraint('isbn')
    )
    op.create_table('user_book',
    sa.Column('userbook_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('mark_read', sa.Boolean(), nullable=True),
    sa.Column('to_read', sa.Boolean(), nullable=True),
    sa.Column('top_five', sa.Integer(), nullable=True),
    sa.Column('enjoyment', sa.Float(), nullable=True),
    sa.Column('aura', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('userbook_id'),
    sa.UniqueConstraint('book_id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_book')
    op.drop_table('book')
    # ### end Alembic commands ###
