"""allow null personas

Revision ID: 5bb89ac85c91
Revises: 6891137f221e
Create Date: 2026-05-31 17:27:16.580254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bb89ac85c91'
down_revision = '6891137f221e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('author', sa.String(length=250), nullable=False),
    sa.Column('publisher', sa.String(length=250), nullable=False),
    sa.Column('isbn', sa.String(length=20), nullable=True),
    sa.Column('cover_id', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('year_published', sa.Integer(), nullable=True),
    sa.Column('genre', sa.String(length=250), nullable=False),
    sa.Column('length', sa.String(length=250), nullable=True),
    sa.Column('agg_enjoyment', sa.Float(), nullable=True),
    sa.Column('agg_aura', sa.Float(), nullable=False),
    sa.Column('persona_one', sa.String(length=250), nullable=True),
    sa.Column('persona_two', sa.String(length=250), nullable=True),
    sa.Column('persona_three', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cover_id'),
    sa.UniqueConstraint('isbn')
    )
    op.create_table('personas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=250), nullable=False),
    sa.Column('password_hash', sa.String(length=250), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('author_books',
    sa.Column('authorbook_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('authorbook_id')
    )
    op.create_table('book_persona_aggregates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'persona_id', name='unique_book_persona')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=1000), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('author_comment', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('mark_read', sa.Boolean(), nullable=True),
    sa.Column('to_read', sa.Boolean(), nullable=True),
    sa.Column('top_five', sa.Integer(), nullable=True),
    sa.Column('enjoyment', sa.Float(), nullable=True),
    sa.Column('aura', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'book_id', name='unique_user_book')
    )
    op.create_table('user_persona_aggregates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'persona_id', name='unique_user_persona')
    )
    op.create_table('user_book_personas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userbook_id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('ranking', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.ForeignKeyConstraint(['userbook_id'], ['user_books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_book_personas')
    op.drop_table('user_persona_aggregates')
    op.drop_table('user_books')
    op.drop_table('comments')
    op.drop_table('book_persona_aggregates')
    op.drop_table('author_books')
    op.drop_table('users')
    op.drop_table('personas')
    op.drop_table('books')
    # ### end Alembic commands ###
